### ISSUE TITLE
HU01-Consultar catálogo de álbumes

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#1]
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger los que más me interesan.

- [ ] [T1HU01-Maquetación interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/9)
- [ ] [T2HU01-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/10)
- [ ] [T3HU01-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/11)
- [ ] [T4HU01-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/12)
- [ ] [T5HU01-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/13)
- [ ] [T6HU01-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/14)
- [ ] [T7HU01-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/15)
- [ ] [T8HU01-Actualizar documento de arquitectura ](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/16)
- [ ] [T9HU01-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/17)
