### ISSUE TITLE
HU02-Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#2]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.

- [ ] [T10HU02-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/18)
- [ ] [T11HU02-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/19)
- [ ] [T12HU02-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/20)
- [ ] [T13HU02-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/21)
- [ ] [T14HU02-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/22)
- [ ] [T15HU02-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/23)
- [ ] [T16HU02-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/24)
- [ ] [T17HU02-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/25)
- [ ] [T18HU02-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/26)
