### ISSUE TITLE
HU03-Consultar el listado de artistas

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#3]
Como usuario visitante quiero ver el listado de artistas para escoger los que más me interesen.

- [x] [T19HU03-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/27)
- [x] [T20HU03-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/28)
- [x] [T21HU03-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/29)
- [x] [T22HU03-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/30)
- [x] [T23HU03-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/31)
- [x] [T24HU03-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/32)
- [x] [T25HU03-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/33)
- [x] [T26HU03-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/34)
- [x] [T27HU03-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/35)
