### ISSUE TITLE
HU04-Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#4]
Como usuario visitante quiero ver el detalle de un artista para ampliar la información sobre él.

- [x] [T28HU04-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/36)
- [x] [T29HU04-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/37)
- [x] [T30HU04-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/38)
- [x] [T31HU04-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/39)
- [x] [T32HU04-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/40)
- [x] [T33HU04-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/41)
- [x] [T34HU04-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/42)
- [x] [T35HU04-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/43)
- [x] [T36HU04-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/44)
