### ISSUE TITLE
HU05-Consultar el listado de coleccionistas

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#5]
Como usuario visitante quiero consultar el listado de coleccionistas para seleccionar el que más me interese.

- [x] [T37HU05-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/45)
- [x] [T38HU05-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/46)
- [x] [T39HU05-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/47)
- [x] [T40HU05-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/48)
- [x] [T41HU05-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/49)
- [x] [T42HU05-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/50)
- [x] [T43HU05-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/51)
- [x] [T44HU05-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/52)
- [x] [T45HU05-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/53)
