### ISSUE TITLE
HU07-Crear un álbum

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#7]
Como coleccionista quiero agregar un álbum al listado.

- [ ] [T55HU07-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/63)
- [ ] [T56HU07-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/64)
- [ ] [T57HU07-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/65)
- [ ] [T58HU07-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/66)
- [ ] [T59HU07-Validar campos de entradas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/67)
- [ ] [T60HU07-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/68)
- [ ] [T61HU07-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/69)
- [ ] [T62HU07-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/70)
- [ ] [T63HU07-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/71)
- [ ] [T64HU07-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/72)

**Comment by hvaron83** [comment]
Se completa el desarrollo e implementación de la historia de usuario.
