### ISSUE TITLE
HU08-Asociar tracks con un álbum

### ISSUE THREAD

**Issue by hvaron83** [hvaron83/MISW-4203-Moviles-EquipoDinamita#8]
Como coleccionista quiero agregar tracks aun álbum para actualizar el catálogo.

- [ ] [T65HU08-Maquetación de la interfaz](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/73)
- [ ] [T66HU08-Consumir servicio backend](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/74)
- [ ] [T67HU08-Implementar el controlador de la vista](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/75)
- [ ] [T68HU08-Implementar el modelo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/76)
- [ ] [T69HU08-Validar campos de entradas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/77)
- [ ] [T70HU08-Pruebas en dispositivo](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/78)
- [ ] [T71HU08-Pruebas de interfaz (espresso)](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/79)
- [ ] [T72HU08-Diseñar y construir pruebas unitarias](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/80)
- [ ] [T73HU08-Actualizar documento de arquitectura](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/81)
- [ ] [T74HU08-Actualizar documento estrategia de pruebas](https://github.com/hvaron83/MISW-4203-Moviles-EquipoDinamita/issues/82)

**Comment by hvaron83** [comment]
Se completan tareas para el desarrollo de la historia de usuario.
